language: go
go: '1.13.x'
env:
  - GO111MODULE=on
install:
  - make setup
script:
  - make ci
deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash -s -- --rm-dist
    on:
      tags: true
